# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # or "pip", "maven", etc.
    directory: "/"           # Location of your package.json or requirements.txt
    schedule:
      interval: "daily"      # Can be "daily", "weekly", or "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"  # You can choose "direct", "indirect", or "all"

